# Generated by Django 4.2.23 on 2026-03-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0214_judge0language_alter_contest_authors_and_more'),
        ('judge', '0219_problemdata_zipfile_size_alter_contest_authors_and_more'),
    ]

    operations = [
    ]
