# Generated by Django 4.2.29 on 2026-04-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0220_merge_20260305_1002'),
        ('judge', '0220_problem_deleted_at'),
    ]

    operations = [
    ]
