# Generated by Django 4.2.29 on 2026-04-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0221_merge_20260414_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='sample_input',
            field=models.TextField(blank=True, help_text='Sample input for "Run Code". Used when no test case is marked as sample.', verbose_name='sample input'),
        ),
        migrations.AddField(
            model_name='problemdata',
            name='sample_output',
            field=models.TextField(blank=True, help_text='Expected sample output. Shown to users alongside their output.', verbose_name='sample output'),
        ),
        migrations.AddField(
            model_name='problemtestcase',
            name='is_sample',
            field=models.BooleanField(default=False, help_text='Sample cases are shown to users and used for "Run Code".', verbose_name='case is sample?'),
        ),
    ]
